plugins {
    alias(libs.plugins.android.application)
    alias libs.plugins.android.secrets
}

android {
    namespace = 'dev.minkin.ingot'
    compileSdk {
        version = release(37)
    }

    defaultConfig {
        applicationId "dev.minkin.ingot"
        minSdk 34
        targetSdk 37
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            optimization {
                enable = false
            }
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    buildFeatures {
        buildConfig = true // Enables the generation of the BuildConfig class
    }


}

dependencies {
    implementation libs.activity.ktx
    implementation libs.appcompat
    implementation libs.constraintlayout
    implementation libs.material
    testImplementation libs.junit
    testImplementation libs.mockito.core
    androidTestImplementation libs.espresso.core
    androidTestImplementation libs.ext.junit
    implementation libs.engine
    implementation libs.retrofit
    implementation libs.retrofit.converter.jackson

    implementation libs.room.runtime
    annotationProcessor libs.room.compiler

    compileOnly libs.lombok
    annotationProcessor libs.lombok
    testCompileOnly libs.lombok
    testAnnotationProcessor libs.lombok
    androidTestCompileOnly libs.lombok
    androidTestAnnotationProcessor libs.lombok
}